using HouseVictoria.Core.Models;

namespace HouseVictoria.Core.Interfaces
{
    /// <summary>
    /// Interface for AI-generated file creation and management
    /// </summary>
    public interface IFileGenerationService
    {
        /// <summary>
        /// Creates a text file with the specified content and saves it to the file retrieval location
        /// </summary>
        Task<string> CreateTextFileAsync(string fileName, string content, string? subdirectory = null);
        
        /// <summary>
        /// Creates a file with the specified content and extension
        /// </summary>
        Task<string> CreateFileAsync(string fileName, byte[] content, string? subdirectory = null);
        
        /// <summary>
        /// Gets all generated files available for retrieval
        /// </summary>
        Task<List<GeneratedFile>> GetGeneratedFilesAsync();
        
        /// <summary>
        /// Gets the file path for a generated file
        /// </summary>
        Task<string?> GetFilePathAsync(string fileName);
        
        /// <summary>
        /// Deletes a generated file
        /// </summary>
        Task<bool> DeleteFileAsync(string fileName);
    }

    /// <summary>
    /// Represents a file generated by the AI
    /// </summary>
    public class GeneratedFile
    {
        public string FileName { get; set; } = string.Empty;
        public string FilePath { get; set; } = string.Empty;
        public long FileSize { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public string? CreatedBy { get; set; } // AI Contact ID
    }
}
