using HouseVictoria.Core.Models;

namespace HouseVictoria.Core.Utils
{
    /// <summary>
    /// Writes ~/.house_victoria/unreal_editor.env so the MCP process can read
    /// Remote Control URL and write-allow without sharing the WPF process env.
    /// </summary>
    public static class UnrealEditorEnvHandoff
    {
        public const string EnvFileName = "unreal_editor.env";

        public static string GetEnvFilePath()
        {
            var dir = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
                ".house_victoria");
            return Path.Combine(dir, EnvFileName);
        }

        public static void Write(AppConfig config)
        {
            if (config == null)
                throw new ArgumentNullException(nameof(config));

            var path = GetEnvFilePath();
            var dir = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(dir))
                Directory.CreateDirectory(dir);

            var url = string.IsNullOrWhiteSpace(config.UnrealRemoteControlUrl)
                ? "http://127.0.0.1:30010"
                : config.UnrealRemoteControlUrl.Trim().TrimEnd('/');
            var write = config.AllowUnrealEditorControl ? "1" : "0";

            var contents =
                "# Generated by House Victoria — do not commit secrets here.\n" +
                $"HOUSE_VICTORIA_UNREAL_RC_URL={url}\n" +
                $"HOUSE_VICTORIA_UNREAL_EDITOR_WRITE={write}\n";

            File.WriteAllText(path, contents);
        }
    }
}
